# Generated by Django 5.1.2 on 2024-10-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_journal_entry_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='auth/'),
        ),
    ]
