# Generated by Django 5.1.2 on 2024-11-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0002_profile_delete_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
