# Generated by Django 5.1.2 on 2024-11-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField(unique=True)),
                ('intent_matched', models.CharField(max_length=255)),
                ('response_given', models.TextField()),
                ('increment', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
